#! /bin/sh

sxhkd &
dunst -config .config/dunst/dunstrc &
compton --config ~/.config/compton/compton.conf
nitrogen --restore &
polybar top &
thunar --daemon &
setxkbmap -layout us,ru -option "grp:ctrl_shift_toggle" &
xautolock -time 15 -locker "~/scripts/lock.sh" -notify 30 -notifier "notify-send -u critical -t 10000 -- 'Locking screen in 30 seconds'" &
mpd ~/.config/mpd/mpd.conf &


bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^1' state=floating follow=on
bspc rule -a urxvt desktop='^2' state=floating
bspc rule -a thunar desktop='^3'
